### ISSUE TITLE
Cannot read property 'bottom' of undefined.

### ISSUE THREAD

**Issue by DeividasBakanas** [huangbinjie/react-scroll#11]
If you have long list and scroll it very fast, package fails with an error:

![image](https://user-images.githubusercontent.com/13733045/38925565-ad80281a-4308-11e8-901e-95a70a435e46.png)

While `very fast` scroll is hard to reproduce I reproduced same error in other way:
https://codesandbox.io/s/8lzrq489qj

Steps to reproduce:
1. Press button `Scroll to bottom`;
2. Scroll down for a while and you'll get an error.

I also get `Cannot read property 'top' of undefined`  time to time, but I could not reproduce it.

**Comment by huangbinjie** [comment]
Thank you very much. 2.x version really have many bugs. I'll fix it as soon as possible.

**Comment by huangbinjie** [comment]
2.0.2-alpha has fixed this bug. Can you take a look?

**Comment by g770728y** [comment]
https://codesandbox.io/s/kmowxk6w83运行，仍然有此问题（滚动很快时发生）。注意了一下package.json，react-iscroller是2.0.4。
我在本地重建项目后，使用相同的代码，一样报错。
是否reopen此issue?
@huangbinjie
