### ISSUE TITLE
Release 2.0.4 on NPM

### ISSUE THREAD

**Issue by LewisW** [huangbinjie/react-scroll#12]
Thanks for the great scrolling library. I've honestly tried 20+ different react virtual scrolling libraries and non have come close to how stable and smooth this one is, so great work!

Any chance you could release 2.0.4 on NPM?

**Comment by huangbinjie** [comment]
Thanks for your response. I actually maintained two different version 1.x and 2.x on npm.
You can install 2.x directly by version tag.
```
npm i react-iscroller@2.0.4
```

**Comment by LewisW** [comment]
Brilliant, thank you!
