### ISSUE TITLE
能提供一个滚动到底部的方法吗

### ISSUE THREAD

**Issue by mybedhome** [huangbinjie/react-scroll#13]
我在做一个聊天室功能，当聊天室接收到新消息的时候，需要自动滚动到最底部，能否提供一个这样的方法？

**Comment by huangbinjie** [comment]
可以用 onScroll 保存这个 dom。然后有消息进来的时候改 scrollTop 就好了...

**Comment by huangbinjie** [comment]
@mybedhome 没啥事我就关了哈。
