### ISSUE TITLE
Event listeners are not removed on unmount. 

### ISSUE THREAD

**Issue by AurimasGaidys** [huangbinjie/react-scroll#2]
When component is unmounted window `resize` event listener removal should be performed.

In `scroller.tsx` (https://github.com/huangbinjie/react-scroll/blob/master/src/scroller.tsx#L93)
Window `resize` listener is added. 
This listener should be removed on `componentWillUnmount`.

I can create pull request.

**Comment by huangbinjie** [comment]
Thanks for your pull request.

**Comment by AurimasGaidys** [comment]
@huangbinjie can you publish package's update to NPM ?

**Comment by huangbinjie** [comment]
@AurimasGaidys 1.1.4 have published. Thank you for your support.

**Comment by AurimasGaidys** [comment]
Thanks!
