### ISSUE TITLE
Component crash if less than 4 items are rendered. 

### ISSUE THREAD

**Issue by AurimasGaidys** [huangbinjie/react-scroll#5]
I tried rendering less than 4 list items and `Cannot read property 'top' of undefined` error is displayed.

It appears that this code might be causing the error: 
[https://github.com/huangbinjie/react-scroll/blob/master/src/scroller.tsx#L200](url)

Can you take a look?

**Comment by huangbinjie** [comment]
It's a legacy problem.
When items have been loaded, The anchor will be set to the third item. As you can see, before your scroll to the fourth item, The component neither calculates nor updates.
I will fix it in next version.

**Comment by DeividasBakanas** [comment]
I want to thank you for this package.
I also have the exact issue. I was wondering when next package version is planned?

**Comment by huangbinjie** [comment]
@DeividasBakanas next week.

**Comment by huangbinjie** [comment]
I have published a new version 1.1.5, does this version solve your issue?

**Comment by DeividasBakanas** [comment]
Thank you, this version solves the problem :)
