### ISSUE TITLE
Cannot read property 'index' of undefined.

### ISSUE THREAD

**Issue by DeividasBakanas** [huangbinjie/react-scroll#6]
Getting this error when list item height dynamically changes and scroll down is performed.

Error:
![image](https://user-images.githubusercontent.com/13733045/38325610-20b541de-384c-11e8-9cd6-d2bd55f6bb95.png)

Reproduced issue:
https://codesandbox.io/s/j30zmly425

Line that causes failure (`anchor` is undefined):
https://github.com/huangbinjie/react-scroll/blob/master/src/projector.ts#L105

Could you take a look?

**Comment by huangbinjie** [comment]
it's my bad. 
The remeasure api has a little bug, and i have dropped it in this version. The only way to detect item height changes is `window.resize`. You can give your dynamic content a certain height that may cause item height changes(eg. Image tag), just like Twitter does now.
In next version, i will support the real dynamic height .

**Comment by DonatasBrazionis** [comment]
When planned to release next package version?

**Comment by huangbinjie** [comment]
I released the dynamic height version 2.0.0-alpha right now. 
This is the online demo: https://codesandbox.io/s/k5jz9yl5lr

**Comment by DeividasBakanas** [comment]
I tried to use 2.0.0-alpha. I ran into another error:
![image](https://user-images.githubusercontent.com/13733045/38887862-aaa8ebc6-4282-11e8-8544-a548c17b3de8.png)

Reproduced issue:
https://codesandbox.io/s/kkr1k1w7lv

Steps to reproduce:
1. Click on dropdown header with text `CLICK ME TO COLLAPSE!`;
2. Scroll to the bottom of the list.

**Comment by huangbinjie** [comment]
@DeividasBakanas bug fixed in 2.0.2-alpha. Please note that `measure` will trigger automatically in 2.x version and i had dropped the measure method in `onRenderCell`.
