### ISSUE TITLE
No item update (rerender) after `items` changed.

### ISSUE THREAD

**Issue by DeividasBakanas** [huangbinjie/react-scroll#7]
I found that `onRenderCell` was not called after `items` array updated.

Line that causes wrong behavior:
https://github.com/huangbinjie/react-scroll/blob/master/src/item.tsx#L23

Currently `Item` is updated only if `itemIndex` has been changed. It should also trigger an update if `item` object is updated.

**Comment by huangbinjie** [comment]
Thank you~

**Comment by huangbinjie** [comment]
Hi, i have merged your code and test ok. A new small version has been published now.

**Comment by DeividasBakanas** [comment]
Thanks, I tested it too :) Works :)
